# This is workflow name
name: hello

# runs on a trigger
on:
  push:
    branches: [main]

# these are jobs inside the workflow
jobs:

  # this is the name of the job
  greet:
    # this is github runner, each job runs on a runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to the users
        run: echo "hello brev"

      - name: say hello to username
        run: echo "Hello $USER"
