# This is workflow name
name: hello

# runs on a trigger
on: 
  push:
    branches: main
    paths: 
      - '**.html'

# these are jobs inside the workflow
jobs:

  # this is the name of the job
  greet:
    # this is github runner, each job runs on a runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to the users
        run: echo "hello brev"

      - name: say hello to username
        run: echo "Hello $USER"
      
      - name: Print Current Date and Time
        run: date

      - name: Print Branch Name
        run: |
          echo "Branch: ${{ github.ref_name }}"
      
      - name: List Repository Files
        run: ls -la
      
      - name: Print Runner Operating System
        run: |
          echo "Runner OS: $RUNNER_OS"
              
  details:
    runs-on: ubuntu-latest
    steps:
      - name: version of python, docker, etc
        run: docker --version && python --version
